export type IconVariant = "duotone" | "outline" | "filled";
export type IconVariantFilter = "all" | IconVariant;

export const ICON_CATEGORIES = [
  "accessibility",
  "account",
  "animals",
  "arrows",
  "buildings",
  "charts",
  "communication",
  "connectivity",
  "cursors",
  "design",
  "development",
  "devices",
  "emoji",
  "files",
  "finance",
  "food-beverage",
  "gaming",
  "home",
  "layout",
  "mail",
  "math",
  "medical",
  "multimedia",
  "nature",
  "navigation",
  "notifications",
  "people",
  "photography",
  "science",
  "seasons",
  "security",
  "shapes",
  "shopping",
  "social",
  "sports",
  "sustainability",
  "text",
  "time",
  "tools",
  "transportation",
  "travel",
  "weather",
] as const;

export type IconCategory = (typeof ICON_CATEGORIES)[number];

export interface IconCatalogItem {
  name: string;
  title: string;
  category: IconCategory;
  tags: string[];
  variant: IconVariant;
  variants: readonly IconVariant[];
}

export interface CategoryInfo {
  id: "all" | IconCategory;
  label: string;
  count: number;
}

// Vite static raw SVG imports
const duotoneSvgModules = import.meta.glob("./duotone/*.svg", {
  eager: true,
  import: "default",
  query: "?raw",
}) as Record<string, string>;
const filledSvgModules = import.meta.glob("./filled/*.svg", {
  eager: true,
  import: "default",
  query: "?raw",
}) as Record<string, string>;

const svgModules: Record<"duotone" | "filled", Record<string, string>> = {
  duotone: duotoneSvgModules,
  filled: filledSvgModules,
};

const VARIANT_ORDER: readonly IconVariant[] = ["outline", "duotone", "filled"];

const variantModules: Record<IconVariant, Record<string, string>> = {
  outline: duotoneSvgModules,
  duotone: duotoneSvgModules,
  filled: filledSvgModules,
};

function hasIconSvg(modules: Record<string, string>, name: string) {
  return Object.keys(modules).some((path) => path.endsWith(`/${name}.svg`));
}

export function getIconVariants(name: string): readonly IconVariant[] {
  return VARIANT_ORDER.filter((variant) =>
    hasIconSvg(variantModules[variant], name)
  );
}

function getDefaultIconVariant(name: string): IconVariant {
  const variants = getIconVariants(name);
  return variants.includes("duotone") ? "duotone" : (variants[0] ?? "outline");
}

function getIconVariantCount(
  item: IconCatalogItem,
  variant: IconVariantFilter
) {
  if (variant === "all") {
    // The All filter represents the catalog-visible Duotone and Filled entries.
    return item.variants.filter((itemVariant) => itemVariant !== "outline")
      .length;
  }

  return item.variants.includes(variant) ? 1 : 0;
}

export const ICON_CATALOG: readonly IconCatalogItem[] = [
  {
    name: "house",
    title: "House",
    category: "buildings",
    tags: [
      "home",
      "living",
      "building",
      "residence",
      "architecture",
      "house",
      "dashboard",
      "navigation",
    ],
    variant: getDefaultIconVariant("house"),
    variants: getIconVariants("house"),
  },
  {
    name: "map-pin",
    title: "Map Pin",
    category: "navigation",
    tags: ["location", "waypoint", "marker", "drop", "map-pin"],
    variant: getDefaultIconVariant("map-pin"),
    variants: getIconVariants("map-pin"),
  },
  {
    name: "bell",
    title: "Bell",
    category: "account",
    tags: ["alarm", "notification", "sound", "reminder", "bell"],
    variant: getDefaultIconVariant("bell"),
    variants: getIconVariants("bell"),
  },
  {
    name: "folder",
    title: "Folder",
    category: "files",
    tags: ["directory", "folder", "file", "storage", "archive"],
    variant: getDefaultIconVariant("folder"),
    variants: getIconVariants("folder"),
  },
  {
    name: "mail",
    title: "Mail",
    category: "text",
    tags: ["email", "message", "letter", "unread", "mail"],
    variant: getDefaultIconVariant("mail"),
    variants: getIconVariants("mail"),
  },
  {
    name: "chevron-right",
    title: "Chevron Right",
    category: "arrows",
    tags: [
      "forward",
      "next",
      "more than",
      "greater",
      "menu",
      "code",
      "coding",
      "command line",
      "terminal",
      "prompt",
      "shell",
      ">",
      "chevron-right",
      "arrow",
      "right",
      "chevron",
    ],
    variant: getDefaultIconVariant("chevron-right"),
    variants: getIconVariants("chevron-right"),
  },
  {
    name: "chevron-down",
    title: "Chevron Down",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "slow",
      "dropdown",
      "chevron-down",
      "arrow",
      "down",
      "expand",
      "chevron",
      "bottom",
    ],
    variant: getDefaultIconVariant("chevron-down"),
    variants: getIconVariants("chevron-down"),
  },
  {
    name: "check",
    title: "Check",
    category: "notifications",
    tags: [
      "done",
      "todo",
      "tick",
      "complete",
      "task",
      "check",
      "confirm",
      "success",
      "verify",
      "ok",
    ],
    variant: getDefaultIconVariant("check"),
    variants: getIconVariants("check"),
  },
  {
    name: "x",
    title: "X",
    category: "notifications",
    tags: [
      "cancel",
      "close",
      "cross",
      "delete",
      "ex",
      "remove",
      "times",
      "clear",
      "math",
      "multiply",
      "multiplication",
      "x",
      "error",
    ],
    variant: getDefaultIconVariant("x"),
    variants: getIconVariants("x"),
  },
  {
    name: "plus",
    title: "Plus",
    category: "math",
    tags: [
      "add",
      "new",
      "increase",
      "increment",
      "positive",
      "calculate",
      "toolbar",
      "crosshair",
      "aim",
      "target",
      "scope",
      "sight",
      "reticule",
      "maximum",
      "upgrade",
      "extra",
      "+",
      "plus",
      "create",
      "more",
    ],
    variant: getDefaultIconVariant("plus"),
    variants: getIconVariants("plus"),
  },
  {
    name: "search",
    title: "Search",
    category: "text",
    tags: [
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
      "lens",
      "locate",
      "explore",
      "discover",
      "enlarge",
      "zoom",
      "search",
      "magnifying-glass",
      "lookup",
      "query",
    ],
    variant: getDefaultIconVariant("search"),
    variants: getIconVariants("search"),
  },
  {
    name: "loader-circle",
    title: "Loader Circle",
    category: "cursors",
    tags: [
      "loading",
      "wait",
      "busy",
      "progress",
      "spinner",
      "spinning",
      "throbber",
      "circle",
      "loader-circle",
      "waiting",
      "status",
      "loader",
    ],
    variant: getDefaultIconVariant("loader-circle"),
    variants: getIconVariants("loader-circle"),
  },
  {
    name: "triangle-alert",
    title: "Triangle Alert",
    category: "notifications",
    tags: [
      "warning",
      "alert",
      "danger",
      "exclamation mark",
      "linter",
      "triangle-alert",
      "exclamation",
      "caution",
    ],
    variant: getDefaultIconVariant("triangle-alert"),
    variants: getIconVariants("triangle-alert"),
  },
  {
    name: "info",
    title: "Info",
    category: "accessibility",
    tags: [
      "about",
      "advice",
      "clue",
      "details",
      "help",
      "hint",
      "indicator",
      "information",
      "knowledge",
      "notice",
      "status",
      "support",
      "tooltip",
      "info",
    ],
    variant: getDefaultIconVariant("info"),
    variants: getIconVariants("info"),
  },
  {
    name: "arrow-right",
    title: "Arrow Right",
    category: "arrows",
    tags: [
      "forward",
      "next",
      "direction",
      "east",
      "->",
      "arrow-right",
      "arrow",
      "right",
    ],
    variant: getDefaultIconVariant("arrow-right"),
    variants: getIconVariants("arrow-right"),
  },
  {
    name: "arrow-big-down-dash",
    title: "Arrow Big Down Dash",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "slow",
      "direction",
      "south",
      "download",
      "arrow-big-down-dash",
      "navigation",
      "arrow",
      "big",
      "down",
      "dash",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-down-dash"),
    variants: getIconVariants("arrow-big-down-dash"),
  },
  {
    name: "arrow-big-down",
    title: "Arrow Big Down",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "direction",
      "south",
      "arrow-big-down",
      "navigation",
      "arrow",
      "big",
      "down",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-down"),
    variants: getIconVariants("arrow-big-down"),
  },
  {
    name: "arrow-big-left-dash",
    title: "Arrow Big Left Dash",
    category: "arrows",
    tags: [
      "previous",
      "back",
      "direction",
      "west",
      "turn",
      "corner",
      "arrow-big-left-dash",
      "navigation",
      "arrow",
      "big",
      "left",
      "dash",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-left-dash"),
    variants: getIconVariants("arrow-big-left-dash"),
  },
  {
    name: "arrow-big-left",
    title: "Arrow Big Left",
    category: "arrows",
    tags: [
      "previous",
      "back",
      "direction",
      "west",
      "indicate turn",
      "arrow-big-left",
      "navigation",
      "arrow",
      "big",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-left"),
    variants: getIconVariants("arrow-big-left"),
  },
  {
    name: "arrow-big-right-dash",
    title: "Arrow Big Right Dash",
    category: "arrows",
    tags: [
      "next",
      "forward",
      "direction",
      "east",
      "turn",
      "corner",
      "arrow-big-right-dash",
      "navigation",
      "arrow",
      "big",
      "right",
      "dash",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-right-dash"),
    variants: getIconVariants("arrow-big-right-dash"),
  },
  {
    name: "arrow-big-right",
    title: "Arrow Big Right",
    category: "arrows",
    tags: [
      "next",
      "forward",
      "direction",
      "east",
      "indicate turn",
      "arrow-big-right",
      "navigation",
      "arrow",
      "big",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-right"),
    variants: getIconVariants("arrow-big-right"),
  },
  {
    name: "arrow-big-up-dash",
    title: "Arrow Big Up Dash",
    category: "arrows",
    tags: [
      "caps lock",
      "capitals",
      "keyboard",
      "button",
      "mac",
      "forward",
      "direction",
      "north",
      "faster",
      "speed",
      "boost",
      "arrow-big-up-dash",
      "navigation",
      "arrow",
      "big",
      "up",
      "dash",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-up-dash"),
    variants: getIconVariants("arrow-big-up-dash"),
  },
  {
    name: "arrow-big-up",
    title: "Arrow Big Up",
    category: "arrows",
    tags: [
      "shift",
      "keyboard",
      "button",
      "mac",
      "capitalize",
      "capitalise",
      "forward",
      "direction",
      "north",
      "arrow-big-up",
      "navigation",
      "arrow",
      "big",
      "up",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-big-up"),
    variants: getIconVariants("arrow-big-up"),
  },
  {
    name: "arrow-down-0-1",
    title: "Arrow Down 0 1",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "numerical",
      "arrow-down-0-1",
      "navigation",
      "arrow",
      "down",
      "0",
      "1",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-0-1"),
    variants: getIconVariants("arrow-down-0-1"),
  },
  {
    name: "arrow-down-1-0",
    title: "Arrow Down 1 0",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "numerical",
      "arrow-down-1-0",
      "navigation",
      "arrow",
      "down",
      "1",
      "0",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-1-0"),
    variants: getIconVariants("arrow-down-1-0"),
  },
  {
    name: "arrow-down-a-z",
    title: "Arrow Down A Z",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "alphabetical",
      "arrow-down-a-z",
      "navigation",
      "arrow",
      "down",
      "a",
      "z",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-a-z"),
    variants: getIconVariants("arrow-down-a-z"),
  },
  {
    name: "arrow-down-from-line",
    title: "Arrow Down From Line",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "direction",
      "south",
      "download",
      "expand",
      "fold",
      "vertical",
      "arrow-down-from-line",
      "navigation",
      "arrow",
      "down",
      "from",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-from-line"),
    variants: getIconVariants("arrow-down-from-line"),
  },
  {
    name: "arrow-down-left",
    title: "Arrow Down Left",
    category: "arrows",
    tags: [
      "direction",
      "south-west",
      "diagonal",
      "arrow-down-left",
      "navigation",
      "arrow",
      "down",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-left"),
    variants: getIconVariants("arrow-down-left"),
  },
  {
    name: "arrow-down-narrow-wide",
    title: "Arrow Down Narrow Wide",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "arrow-down-narrow-wide",
      "navigation",
      "arrow",
      "down",
      "narrow",
      "wide",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-narrow-wide"),
    variants: getIconVariants("arrow-down-narrow-wide"),
  },
  {
    name: "arrow-down-right",
    title: "Arrow Down Right",
    category: "arrows",
    tags: [
      "direction",
      "south-east",
      "diagonal",
      "arrow-down-right",
      "navigation",
      "arrow",
      "down",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-right"),
    variants: getIconVariants("arrow-down-right"),
  },
  {
    name: "arrow-down-to-dot",
    title: "Arrow Down To Dot",
    category: "arrows",
    tags: [
      "direction",
      "south",
      "waypoint",
      "location",
      "step",
      "into",
      "arrow-down-to-dot",
      "navigation",
      "arrow",
      "down",
      "to",
      "dot",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-to-dot"),
    variants: getIconVariants("arrow-down-to-dot"),
  },
  {
    name: "arrow-down-to-line",
    title: "Arrow Down To Line",
    category: "arrows",
    tags: [
      "behind",
      "direction",
      "south",
      "download",
      "save",
      "git",
      "version control",
      "pull",
      "collapse",
      "fold",
      "vertical",
      "arrow-down-to-line",
      "navigation",
      "arrow",
      "down",
      "to",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-to-line"),
    variants: getIconVariants("arrow-down-to-line"),
  },
  {
    name: "arrow-down-up",
    title: "Arrow Down Up",
    category: "arrows",
    tags: [
      "bidirectional",
      "two-way",
      "2-way",
      "swap",
      "switch",
      "network",
      "traffic",
      "flow",
      "mobile data",
      "internet",
      "sort",
      "reorder",
      "move",
      "arrow-down-up",
      "navigation",
      "arrow",
      "down",
      "up",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-up"),
    variants: getIconVariants("arrow-down-up"),
  },
  {
    name: "arrow-down-wide-narrow",
    title: "Arrow Down Wide Narrow",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "arrow-down-wide-narrow",
      "navigation",
      "arrow",
      "down",
      "wide",
      "narrow",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-wide-narrow"),
    variants: getIconVariants("arrow-down-wide-narrow"),
  },
  {
    name: "arrow-down-z-a",
    title: "Arrow Down Z A",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "alphabetical",
      "reverse",
      "arrow-down-z-a",
      "navigation",
      "arrow",
      "down",
      "z",
      "a",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down-z-a"),
    variants: getIconVariants("arrow-down-z-a"),
  },
  {
    name: "arrow-down",
    title: "Arrow Down",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "direction",
      "south",
      "arrow-down",
      "navigation",
      "arrow",
      "down",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-down"),
    variants: getIconVariants("arrow-down"),
  },
  {
    name: "arrow-left-from-line",
    title: "Arrow Left From Line",
    category: "arrows",
    tags: [
      "previous",
      "back",
      "direction",
      "west",
      "expand",
      "fold",
      "horizontal",
      "<-|",
      "arrow-left-from-line",
      "navigation",
      "arrow",
      "left",
      "from",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-left-from-line"),
    variants: getIconVariants("arrow-left-from-line"),
  },
  {
    name: "arrow-left-right",
    title: "Arrow Left Right",
    category: "arrows",
    tags: [
      "bidirectional",
      "two-way",
      "2-way",
      "swap",
      "switch",
      "transaction",
      "reorder",
      "move",
      "<-",
      "->",
      "arrow-left-right",
      "navigation",
      "arrow",
      "left",
      "right",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-left-right"),
    variants: getIconVariants("arrow-left-right"),
  },
  {
    name: "arrow-left-to-line",
    title: "Arrow Left To Line",
    category: "arrows",
    tags: [
      "previous",
      "back",
      "direction",
      "west",
      "collapse",
      "fold",
      "horizontal",
      "|<-",
      "arrow-left-to-line",
      "navigation",
      "arrow",
      "left",
      "to",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-left-to-line"),
    variants: getIconVariants("arrow-left-to-line"),
  },
  {
    name: "arrow-left",
    title: "Arrow Left",
    category: "arrows",
    tags: [
      "previous",
      "back",
      "direction",
      "west",
      "<-",
      "arrow-left",
      "navigation",
      "arrow",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-left"),
    variants: getIconVariants("arrow-left"),
  },
  {
    name: "arrow-right-from-line",
    title: "Arrow Right From Line",
    category: "arrows",
    tags: [
      "next",
      "forward",
      "direction",
      "east",
      "export",
      "expand",
      "fold",
      "horizontal",
      "|->",
      "arrow-right-from-line",
      "navigation",
      "arrow",
      "right",
      "from",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-right-from-line"),
    variants: getIconVariants("arrow-right-from-line"),
  },
  {
    name: "arrow-right-left",
    title: "Arrow Right Left",
    category: "arrows",
    tags: [
      "bidirectional",
      "two-way",
      "2-way",
      "swap",
      "switch",
      "transaction",
      "reorder",
      "move",
      "<-",
      "->",
      "arrow-right-left",
      "navigation",
      "arrow",
      "right",
      "left",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-right-left"),
    variants: getIconVariants("arrow-right-left"),
  },
  {
    name: "arrow-right-to-line",
    title: "Arrow Right To Line",
    category: "arrows",
    tags: [
      "next",
      "forward",
      "direction",
      "east",
      "tab",
      "keyboard",
      "mac",
      "indent",
      "collapse",
      "fold",
      "horizontal",
      "->|",
      "arrow-right-to-line",
      "navigation",
      "arrow",
      "right",
      "to",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-right-to-line"),
    variants: getIconVariants("arrow-right-to-line"),
  },
  {
    name: "arrow-up-0-1",
    title: "Arrow Up 0 1",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "numerical",
      "arrow-up-0-1",
      "navigation",
      "arrow",
      "up",
      "0",
      "1",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-0-1"),
    variants: getIconVariants("arrow-up-0-1"),
  },
  {
    name: "arrow-up-1-0",
    title: "Arrow Up 1 0",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "numerical",
      "arrow-up-1-0",
      "navigation",
      "arrow",
      "up",
      "1",
      "0",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-1-0"),
    variants: getIconVariants("arrow-up-1-0"),
  },
  {
    name: "arrow-up-a-z",
    title: "Arrow Up A Z",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "alphabetical",
      "arrow-up-a-z",
      "navigation",
      "arrow",
      "up",
      "a",
      "z",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-a-z"),
    variants: getIconVariants("arrow-up-a-z"),
  },
  {
    name: "arrow-up-down",
    title: "Arrow Up Down",
    category: "arrows",
    tags: [
      "bidirectional",
      "two-way",
      "2-way",
      "swap",
      "switch",
      "network",
      "mobile data",
      "internet",
      "sort",
      "reorder",
      "move",
      "arrow-up-down",
      "navigation",
      "arrow",
      "up",
      "down",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-down"),
    variants: getIconVariants("arrow-up-down"),
  },
  {
    name: "arrow-up-from-dot",
    title: "Arrow Up From Dot",
    category: "arrows",
    tags: [
      "direction",
      "north",
      "step",
      "out",
      "arrow-up-from-dot",
      "navigation",
      "arrow",
      "up",
      "from",
      "dot",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-from-dot"),
    variants: getIconVariants("arrow-up-from-dot"),
  },
  {
    name: "arrow-up-from-line",
    title: "Arrow Up From Line",
    category: "arrows",
    tags: [
      "forward",
      "direction",
      "north",
      "upload",
      "git",
      "version control",
      "push",
      "expand",
      "fold",
      "vertical",
      "arrow-up-from-line",
      "navigation",
      "arrow",
      "up",
      "from",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-from-line"),
    variants: getIconVariants("arrow-up-from-line"),
  },
  {
    name: "arrow-up-left",
    title: "Arrow Up Left",
    category: "arrows",
    tags: [
      "direction",
      "north-west",
      "diagonal",
      "arrow-up-left",
      "navigation",
      "arrow",
      "up",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-left"),
    variants: getIconVariants("arrow-up-left"),
  },
  {
    name: "arrow-up-narrow-wide",
    title: "Arrow Up Narrow Wide",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "arrow-up-narrow-wide",
      "navigation",
      "arrow",
      "up",
      "narrow",
      "wide",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-narrow-wide"),
    variants: getIconVariants("arrow-up-narrow-wide"),
  },
  {
    name: "arrow-up-right",
    title: "Arrow Up Right",
    category: "arrows",
    tags: [
      "direction",
      "north-east",
      "diagonal",
      "arrow-up-right",
      "navigation",
      "arrow",
      "up",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-right"),
    variants: getIconVariants("arrow-up-right"),
  },
  {
    name: "arrow-up-to-line",
    title: "Arrow Up To Line",
    category: "arrows",
    tags: [
      "forward",
      "direction",
      "north",
      "upload",
      "collapse",
      "fold",
      "vertical",
      "arrow-up-to-line",
      "navigation",
      "arrow",
      "up",
      "to",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-to-line"),
    variants: getIconVariants("arrow-up-to-line"),
  },
  {
    name: "arrow-up-wide-narrow",
    title: "Arrow Up Wide Narrow",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "arrow-up-wide-narrow",
      "navigation",
      "arrow",
      "up",
      "wide",
      "narrow",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-wide-narrow"),
    variants: getIconVariants("arrow-up-wide-narrow"),
  },
  {
    name: "arrow-up-z-a",
    title: "Arrow Up Z A",
    category: "text",
    tags: [
      "filter",
      "sort",
      "ascending",
      "descending",
      "increasing",
      "decreasing",
      "rising",
      "falling",
      "alphabetical",
      "reverse",
      "arrow-up-z-a",
      "navigation",
      "arrow",
      "up",
      "z",
      "a",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up-z-a"),
    variants: getIconVariants("arrow-up-z-a"),
  },
  {
    name: "arrow-up",
    title: "Arrow Up",
    category: "arrows",
    tags: [
      "forward",
      "direction",
      "north",
      "arrow-up",
      "navigation",
      "arrow",
      "up",
      "directional",
    ],
    variant: getDefaultIconVariant("arrow-up"),
    variants: getIconVariants("arrow-up"),
  },
  {
    name: "arrows-up-from-line",
    title: "Arrows Up From Line",
    category: "arrows",
    tags: [
      "direction",
      "orientation",
      "this way up",
      "vertical",
      "package",
      "box",
      "fragile",
      "postage",
      "shipping",
      "arrows-up-from-line",
      "navigation",
      "arrows",
      "up",
      "from",
      "line",
      "directional",
    ],
    variant: getDefaultIconVariant("arrows-up-from-line"),
    variants: getIconVariants("arrows-up-from-line"),
  },
  {
    name: "chevron-first",
    title: "Chevron First",
    category: "arrows",
    tags: [
      "previous",
      "music",
      "chevron-first",
      "navigation",
      "chevron",
      "first",
      "arrow",
    ],
    variant: getDefaultIconVariant("chevron-first"),
    variants: getIconVariants("chevron-first"),
  },
  {
    name: "chevron-last",
    title: "Chevron Last",
    category: "arrows",
    tags: [
      "skip",
      "next",
      "music",
      "chevron-last",
      "navigation",
      "chevron",
      "last",
      "arrow",
    ],
    variant: getDefaultIconVariant("chevron-last"),
    variants: getIconVariants("chevron-last"),
  },
  {
    name: "chevron-left",
    title: "Chevron Left",
    category: "arrows",
    tags: [
      "back",
      "previous",
      "less than",
      "fewer",
      "menu",
      "<",
      "chevron-left",
      "navigation",
      "chevron",
      "left",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevron-left"),
    variants: getIconVariants("chevron-left"),
  },
  {
    name: "chevron-up",
    title: "Chevron Up",
    category: "arrows",
    tags: [
      "caret",
      "keyboard",
      "mac",
      "control",
      "ctrl",
      "superscript",
      "exponential",
      "power",
      "ahead",
      "fast",
      "^",
      "dropdown",
      "chevron-up",
    ],
    variant: getDefaultIconVariant("chevron-up"),
    variants: getIconVariants("chevron-up"),
  },
  {
    name: "chevrons-down-up",
    title: "Chevrons Down Up",
    category: "arrows",
    tags: [
      "collapse",
      "fold",
      "vertical",
      "chevrons-down-up",
      "navigation",
      "chevrons",
      "down",
      "up",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-down-up"),
    variants: getIconVariants("chevrons-down-up"),
  },
  {
    name: "chevrons-down",
    title: "Chevrons Down",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "slower",
      "chevrons-down",
      "navigation",
      "chevrons",
      "down",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-down"),
    variants: getIconVariants("chevrons-down"),
  },
  {
    name: "chevrons-left-right-ellipsis",
    title: "Chevrons Left Right Ellipsis",
    category: "communication",
    tags: [
      "internet",
      "network",
      "connection",
      "cable",
      "lan",
      "port",
      "router",
      "switch",
      "hub",
      "modem",
      "web",
      "online",
      "networking",
      "communication",
      "socket",
      "plug",
      "slot",
      "controller",
      "connector",
      "interface",
      "console",
      "signal",
      "data",
      "input",
      "output",
      "chevrons-left-right-ellipsis",
      "navigation",
      "chevrons",
      "left",
      "right",
      "ellipsis",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-left-right-ellipsis"),
    variants: getIconVariants("chevrons-left-right-ellipsis"),
  },
  {
    name: "chevrons-left-right",
    title: "Chevrons Left Right",
    category: "arrows",
    tags: [
      "expand",
      "horizontal",
      "unfold",
      "chevrons-left-right",
      "navigation",
      "chevrons",
      "left",
      "right",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-left-right"),
    variants: getIconVariants("chevrons-left-right"),
  },
  {
    name: "chevrons-left",
    title: "Chevrons Left",
    category: "arrows",
    tags: [
      "turn",
      "corner",
      "chevrons-left",
      "navigation",
      "chevrons",
      "left",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-left"),
    variants: getIconVariants("chevrons-left"),
  },
  {
    name: "chevrons-right-left",
    title: "Chevrons Right Left",
    category: "arrows",
    tags: [
      "collapse",
      "fold",
      "horizontal",
      "chevrons-right-left",
      "navigation",
      "chevrons",
      "right",
      "left",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-right-left"),
    variants: getIconVariants("chevrons-right-left"),
  },
  {
    name: "chevrons-right",
    title: "Chevrons Right",
    category: "arrows",
    tags: [
      "turn",
      "corner",
      "chevrons-right",
      "navigation",
      "chevrons",
      "right",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-right"),
    variants: getIconVariants("chevrons-right"),
  },
  {
    name: "chevrons-up-down",
    title: "Chevrons Up Down",
    category: "arrows",
    tags: ["expand", "unfold", "vertical", "chevrons-up-down"],
    variant: getDefaultIconVariant("chevrons-up-down"),
    variants: getIconVariants("chevrons-up-down"),
  },
  {
    name: "chevrons-up",
    title: "Chevrons Up",
    category: "arrows",
    tags: [
      "forward",
      "ahead",
      "faster",
      "speed",
      "boost",
      "chevrons-up",
      "navigation",
      "chevrons",
      "up",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("chevrons-up"),
    variants: getIconVariants("chevrons-up"),
  },
  {
    name: "circle-arrow-down",
    title: "Circle Arrow Down",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "direction",
      "south",
      "sign",
      "button",
      "circle-arrow-down",
      "navigation",
      "circle",
      "arrow",
      "down",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-down"),
    variants: getIconVariants("circle-arrow-down"),
  },
  {
    name: "circle-arrow-left",
    title: "Circle Arrow Left",
    category: "arrows",
    tags: [
      "previous",
      "back",
      "direction",
      "west",
      "sign",
      "turn",
      "button",
      "<-",
      "circle-arrow-left",
      "navigation",
      "circle",
      "arrow",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-left"),
    variants: getIconVariants("circle-arrow-left"),
  },
  {
    name: "circle-arrow-out-down-left",
    title: "Circle Arrow Out Down Left",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "south-west",
      "diagonal",
      "circle-arrow-out-down-left",
      "navigation",
      "circle",
      "arrow",
      "out",
      "down",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-out-down-left"),
    variants: getIconVariants("circle-arrow-out-down-left"),
  },
  {
    name: "circle-arrow-out-down-right",
    title: "Circle Arrow Out Down Right",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "south-east",
      "diagonal",
      "circle-arrow-out-down-right",
      "navigation",
      "circle",
      "arrow",
      "out",
      "down",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-out-down-right"),
    variants: getIconVariants("circle-arrow-out-down-right"),
  },
  {
    name: "circle-arrow-out-up-left",
    title: "Circle Arrow Out Up Left",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "north-west",
      "diagonal",
      "keyboard",
      "button",
      "escape",
      "circle-arrow-out-up-left",
      "navigation",
      "circle",
      "arrow",
      "out",
      "up",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-out-up-left"),
    variants: getIconVariants("circle-arrow-out-up-left"),
  },
  {
    name: "circle-arrow-out-up-right",
    title: "Circle Arrow Out Up Right",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "north-east",
      "diagonal",
      "circle-arrow-out-up-right",
      "navigation",
      "circle",
      "arrow",
      "out",
      "up",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-out-up-right"),
    variants: getIconVariants("circle-arrow-out-up-right"),
  },
  {
    name: "circle-arrow-right",
    title: "Circle Arrow Right",
    category: "arrows",
    tags: [
      "next",
      "forward",
      "direction",
      "east",
      "sign",
      "turn",
      "button",
      "->",
      "circle-arrow-right",
      "navigation",
      "circle",
      "arrow",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-right"),
    variants: getIconVariants("circle-arrow-right"),
  },
  {
    name: "circle-arrow-up",
    title: "Circle Arrow Up",
    category: "arrows",
    tags: [
      "forward",
      "direction",
      "north",
      "sign",
      "button",
      "circle-arrow-up",
      "navigation",
      "circle",
      "arrow",
      "up",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-arrow-up"),
    variants: getIconVariants("circle-arrow-up"),
  },
  {
    name: "circle-chevron-down",
    title: "Circle Chevron Down",
    category: "arrows",
    tags: [
      "back",
      "menu",
      "circle-chevron-down",
      "navigation",
      "circle",
      "chevron",
      "down",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-chevron-down"),
    variants: getIconVariants("circle-chevron-down"),
  },
  {
    name: "circle-chevron-left",
    title: "Circle Chevron Left",
    category: "arrows",
    tags: [
      "back",
      "previous",
      "less than",
      "fewer",
      "menu",
      "<",
      "circle-chevron-left",
      "navigation",
      "circle",
      "chevron",
      "left",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-chevron-left"),
    variants: getIconVariants("circle-chevron-left"),
  },
  {
    name: "circle-chevron-right",
    title: "Circle Chevron Right",
    category: "arrows",
    tags: [
      "back",
      "more than",
      "greater",
      "menu",
      ">",
      "circle-chevron-right",
      "navigation",
      "circle",
      "chevron",
      "right",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-chevron-right"),
    variants: getIconVariants("circle-chevron-right"),
  },
  {
    name: "circle-chevron-up",
    title: "Circle Chevron Up",
    category: "arrows",
    tags: [
      "caret",
      "ahead",
      "menu",
      "^",
      "circle-chevron-up",
      "navigation",
      "circle",
      "chevron",
      "up",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("circle-chevron-up"),
    variants: getIconVariants("circle-chevron-up"),
  },
  {
    name: "square-arrow-down-left",
    title: "Square Arrow Down Left",
    category: "arrows",
    tags: [
      "direction",
      "south-west",
      "diagonal",
      "sign",
      "turn",
      "keyboard",
      "button",
      "square-arrow-down-left",
      "navigation",
      "square",
      "arrow",
      "down",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-down-left"),
    variants: getIconVariants("square-arrow-down-left"),
  },
  {
    name: "square-arrow-down-right",
    title: "Square Arrow Down Right",
    category: "arrows",
    tags: [
      "direction",
      "south-east",
      "diagonal",
      "sign",
      "turn",
      "keyboard",
      "button",
      "square-arrow-down-right",
      "navigation",
      "square",
      "arrow",
      "down",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-down-right"),
    variants: getIconVariants("square-arrow-down-right"),
  },
  {
    name: "square-arrow-down",
    title: "Square Arrow Down",
    category: "arrows",
    tags: [
      "backwards",
      "reverse",
      "direction",
      "south",
      "sign",
      "keyboard",
      "button",
      "square-arrow-down",
      "navigation",
      "square",
      "arrow",
      "down",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-down"),
    variants: getIconVariants("square-arrow-down"),
  },
  {
    name: "square-arrow-left",
    title: "Square Arrow Left",
    category: "arrows",
    tags: [
      "previous",
      "back",
      "direction",
      "west",
      "sign",
      "keyboard",
      "button",
      "<-",
      "square-arrow-left",
      "navigation",
      "square",
      "arrow",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-left"),
    variants: getIconVariants("square-arrow-left"),
  },
  {
    name: "square-arrow-out-down-left",
    title: "Square Arrow Out Down Left",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "south-west",
      "diagonal",
      "square-arrow-out-down-left",
      "navigation",
      "square",
      "arrow",
      "out",
      "down",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-out-down-left"),
    variants: getIconVariants("square-arrow-out-down-left"),
  },
  {
    name: "square-arrow-out-down-right",
    title: "Square Arrow Out Down Right",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "south-east",
      "diagonal",
      "square-arrow-out-down-right",
      "navigation",
      "square",
      "arrow",
      "out",
      "down",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-out-down-right"),
    variants: getIconVariants("square-arrow-out-down-right"),
  },
  {
    name: "square-arrow-out-up-left",
    title: "Square Arrow Out Up Left",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "north-west",
      "diagonal",
      "square-arrow-out-up-left",
      "navigation",
      "square",
      "arrow",
      "out",
      "up",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-out-up-left"),
    variants: getIconVariants("square-arrow-out-up-left"),
  },
  {
    name: "square-arrow-out-up-right",
    title: "Square Arrow Out Up Right",
    category: "arrows",
    tags: [
      "outwards",
      "direction",
      "north-east",
      "diagonal",
      "share",
      "open",
      "external",
      "link",
      "square-arrow-out-up-right",
      "navigation",
      "square",
      "arrow",
      "out",
      "up",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-out-up-right"),
    variants: getIconVariants("square-arrow-out-up-right"),
  },
  {
    name: "square-arrow-right-enter",
    title: "Square Arrow Right Enter",
    category: "arrows",
    tags: [
      "left",
      "in",
      "inside",
      "input",
      "insert",
      "source",
      "import",
      "place",
      "->",
      "square-arrow-right-enter",
      "navigation",
      "square",
      "arrow",
      "right",
      "enter",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-right-enter"),
    variants: getIconVariants("square-arrow-right-enter"),
  },
  {
    name: "square-arrow-right-exit",
    title: "Square Arrow Right Exit",
    category: "arrows",
    tags: [
      "out",
      "outside",
      "output",
      "export",
      "->",
      "square-arrow-right-exit",
      "navigation",
      "square",
      "arrow",
      "right",
      "exit",
      "direction",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-right-exit"),
    variants: getIconVariants("square-arrow-right-exit"),
  },
  {
    name: "square-arrow-right",
    title: "Square Arrow Right",
    category: "arrows",
    tags: [
      "next",
      "forward",
      "direction",
      "west",
      "sign",
      "keyboard",
      "button",
      "->",
      "square-arrow-right",
      "navigation",
      "square",
      "arrow",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-right"),
    variants: getIconVariants("square-arrow-right"),
  },
  {
    name: "square-arrow-up-left",
    title: "Square Arrow Up Left",
    category: "arrows",
    tags: [
      "direction",
      "north-west",
      "diagonal",
      "sign",
      "keyboard",
      "button",
      "square-arrow-up-left",
      "navigation",
      "square",
      "arrow",
      "up",
      "left",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-up-left"),
    variants: getIconVariants("square-arrow-up-left"),
  },
  {
    name: "square-arrow-up-right",
    title: "Square Arrow Up Right",
    category: "arrows",
    tags: [
      "direction",
      "north-east",
      "diagonal",
      "sign",
      "keyboard",
      "button",
      "share",
      "square-arrow-up-right",
      "navigation",
      "square",
      "arrow",
      "up",
      "right",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-up-right"),
    variants: getIconVariants("square-arrow-up-right"),
  },
  {
    name: "square-arrow-up",
    title: "Square Arrow Up",
    category: "arrows",
    tags: [
      "forward",
      "direction",
      "north",
      "sign",
      "keyboard",
      "button",
      "square-arrow-up",
      "navigation",
      "square",
      "arrow",
      "up",
      "directional",
    ],
    variant: getDefaultIconVariant("square-arrow-up"),
    variants: getIconVariants("square-arrow-up"),
  },
  {
    name: "square-chevron-down",
    title: "Square Chevron Down",
    category: "arrows",
    tags: [
      "back",
      "menu",
      "panel",
      "square-chevron-down",
      "navigation",
      "square",
      "chevron",
      "down",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("square-chevron-down"),
    variants: getIconVariants("square-chevron-down"),
  },
  {
    name: "square-chevron-left",
    title: "Square Chevron Left",
    category: "arrows",
    tags: [
      "back",
      "previous",
      "less than",
      "fewer",
      "menu",
      "panel",
      "button",
      "keyboard",
      "<",
      "square-chevron-left",
      "navigation",
      "square",
      "chevron",
      "left",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("square-chevron-left"),
    variants: getIconVariants("square-chevron-left"),
  },
  {
    name: "square-chevron-right",
    title: "Square Chevron Right",
    category: "arrows",
    tags: [
      "forward",
      "next",
      "more than",
      "greater",
      "menu",
      "panel",
      "code",
      "coding",
      "command line",
      "terminal",
      "prompt",
      "shell",
      "console",
      ">",
      "square-chevron-right",
      "navigation",
      "square",
      "chevron",
      "right",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("square-chevron-right"),
    variants: getIconVariants("square-chevron-right"),
  },
  {
    name: "square-chevron-up",
    title: "Square Chevron Up",
    category: "arrows",
    tags: [
      "caret",
      "keyboard",
      "button",
      "mac",
      "control",
      "ctrl",
      "superscript",
      "exponential",
      "power",
      "ahead",
      "menu",
      "panel",
      "^",
      "square-chevron-up",
      "navigation",
      "square",
      "chevron",
      "up",
      "arrow",
      "directional",
    ],
    variant: getDefaultIconVariant("square-chevron-up"),
    variants: getIconVariants("square-chevron-up"),
  },
  {
    name: "star",
    title: "Star",
    category: "account",
    tags: [
      "bookmark",
      "favorite",
      "like",
      "review",
      "rating",
      "star",
      "rate",
      "featured",
    ],
    variant: getDefaultIconVariant("star"),
    variants: getIconVariants("star"),
  },
  {
    name: "bookmark",
    title: "Bookmark",
    category: "account",
    tags: [
      "save",
      "favorite",
      "mark",
      "label",
      "attachment",
      "file",
      "stick",
      "pin",
      "read",
      "clip",
      "marker",
      "tag",
      "bookmark",
      "ribbon",
      "read-later",
    ],
    variant: getDefaultIconVariant("bookmark"),
    variants: getIconVariants("bookmark"),
  },
  {
    name: "copy",
    title: "Copy",
    category: "text",
    tags: [
      "clone",
      "duplicate",
      "multiple",
      "copy",
      "clipboard",
      "file",
      "document",
    ],
    variant: getDefaultIconVariant("copy"),
    variants: getIconVariants("copy"),
  },
  {
    name: "minus",
    title: "Minus",
    category: "math",
    tags: [
      "subtract",
      "remove",
      "decrease",
      "decrement",
      "reduce",
      "negative",
      "calculate",
      "line",
      "divider",
      "separator",
      "horizontal rule",
      "hr",
      "html",
      "markup",
      "markdown",
      "toolbar",
      "operator",
      "code",
      "coding",
      "minimum",
      "downgrade",
      "minus",
      "dash",
      "zoom-out",
    ],
    variant: getDefaultIconVariant("minus"),
    variants: getIconVariants("minus"),
  },
  {
    name: "file-text",
    title: "File Text",
    category: "files",
    tags: [
      "data",
      "txt",
      "pdf",
      "document",
      "file-text",
      "page",
      "text",
      "file",
      "doc",
      "article",
    ],
    variant: getDefaultIconVariant("file-text"),
    variants: getIconVariants("file-text"),
  },
  {
    name: "moon",
    title: "Moon",
    category: "accessibility",
    tags: ["dark", "night", "moon", "theme", "mode", "weather", "crescent"],
    variant: getDefaultIconVariant("moon"),
    variants: getIconVariants("moon"),
  },
  {
    name: "user",
    title: "User",
    category: "account",
    tags: [
      "person",
      "account",
      "contact",
      "user",
      "profile",
      "avatar",
      "member",
      "author",
    ],
    variant: getDefaultIconVariant("user"),
    variants: getIconVariants("user"),
  },
  {
    name: "circle-check",
    title: "Circle Check",
    category: "notifications",
    tags: [
      "done",
      "todo",
      "tick",
      "complete",
      "task",
      "circle-check",
      "check",
      "success",
      "confirmed",
      "verified",
    ],
    variant: getDefaultIconVariant("circle-check"),
    variants: getIconVariants("circle-check"),
  },
  {
    name: "settings",
    title: "Settings",
    category: "account",
    tags: [
      "cog",
      "edit",
      "gear",
      "preferences",
      "settings",
      "configuration",
      "options",
      "controls",
    ],
    variant: getDefaultIconVariant("settings"),
    variants: getIconVariants("settings"),
  },
  {
    name: "heart",
    title: "Heart",
    category: "medical",
    tags: [
      "like",
      "love",
      "emotion",
      "suit",
      "playing",
      "cards",
      "heart",
      "favorite",
      "health",
      "care",
    ],
    variant: getDefaultIconVariant("heart"),
    variants: getIconVariants("heart"),
  },
  {
    name: "trash",
    title: "Trash",
    category: "files",
    tags: [
      "empty",
      "deletion",
      "cleanup",
      "junk",
      "clear",
      "garbage",
      "delete",
      "remove",
      "bin",
      "waste",
      "recycle",
      "discard",
      "binoculars",
      "rubbish",
      "trash",
    ],
    variant: getDefaultIconVariant("trash"),
    variants: getIconVariants("trash"),
  },
  {
    name: "clock",
    title: "Clock",
    category: "time",
    tags: ["time", "watch", "alarm", "clock"],
    variant: getDefaultIconVariant("clock"),
    variants: getIconVariants("clock"),
  },
  {
    name: "calendar",
    title: "Calendar",
    category: "time",
    tags: [
      "date",
      "month",
      "year",
      "event",
      "birthday",
      "birthdate",
      "calendar",
    ],
    variant: getDefaultIconVariant("calendar"),
    variants: getIconVariants("calendar"),
  },
  {
    name: "camera",
    title: "Camera",
    category: "photography",
    tags: [
      "photography",
      "lens",
      "focus",
      "capture",
      "shot",
      "visual",
      "image",
      "device",
      "equipment",
      "photo",
      "webcam",
      "video",
      "camera",
    ],
    variant: getDefaultIconVariant("camera"),
    variants: getIconVariants("camera"),
  },
  {
    name: "video",
    title: "Video",
    category: "devices",
    tags: [
      "camera",
      "movie",
      "film",
      "recording",
      "motion picture",
      "camcorder",
      "reel",
      "video",
    ],
    variant: getDefaultIconVariant("video"),
    variants: getIconVariants("video"),
  },
  {
    name: "image",
    title: "Image",
    category: "photography",
    tags: ["picture", "photo", "image"],
    variant: getDefaultIconVariant("image"),
    variants: getIconVariants("image"),
  },
  {
    name: "music",
    title: "Music",
    category: "multimedia",
    tags: ["note", "quaver", "eighth note", "music"],
    variant: getDefaultIconVariant("music"),
    variants: getIconVariants("music"),
  },
  {
    name: "mic",
    title: "Mic",
    category: "devices",
    tags: [
      "record",
      "sound",
      "listen",
      "radio",
      "podcast",
      "microphone",
      "mic",
    ],
    variant: getDefaultIconVariant("mic"),
    variants: getIconVariants("mic"),
  },
  {
    name: "volume-2",
    title: "Volume 2",
    category: "connectivity",
    tags: ["music", "sound", "speaker", "volume-2"],
    variant: getDefaultIconVariant("volume-2"),
    variants: getIconVariants("volume-2"),
  },
  {
    name: "lock",
    title: "Lock",
    category: "security",
    tags: ["security", "password", "secure", "admin", "lock"],
    variant: getDefaultIconVariant("lock"),
    variants: getIconVariants("lock"),
  },
  {
    name: "lock-open",
    title: "Lock Open",
    category: "security",
    tags: ["security", "lock-open"],
    variant: getDefaultIconVariant("lock-open"),
    variants: getIconVariants("lock-open"),
  },
  {
    name: "key",
    title: "Key",
    category: "security",
    tags: [
      "password",
      "login",
      "authentication",
      "secure",
      "unlock",
      "keychain",
      "key ring",
      "fob",
      "key",
    ],
    variant: getDefaultIconVariant("key"),
    variants: getIconVariants("key"),
  },
  {
    name: "shield",
    title: "Shield",
    category: "account",
    tags: [
      "cybersecurity",
      "secure",
      "safety",
      "protection",
      "guardian",
      "armored",
      "armoured",
      "defense",
      "defence",
      "defender",
      "block",
      "threat",
      "prevention",
      "antivirus",
      "vigilance",
      "vigilant",
      "detection",
      "scan",
      "find",
      "strength",
      "strong",
      "tough",
      "invincible",
      "invincibility",
      "invulnerable",
      "undamaged",
      "audit",
      "admin",
      "verification",
      "crest",
      "bravery",
      "knight",
      "foot soldier",
      "infantry",
      "trooper",
      "pawn",
      "battle",
      "war",
      "military",
      "army",
      "cadet",
      "scout",
      "shield",
    ],
    variant: getDefaultIconVariant("shield"),
    variants: getIconVariants("shield"),
  },
  {
    name: "eye",
    title: "Eye",
    category: "accessibility",
    tags: [
      "view",
      "watch",
      "see",
      "show",
      "expose",
      "reveal",
      "display",
      "visible",
      "visibility",
      "vision",
      "preview",
      "read",
      "eye",
    ],
    variant: getDefaultIconVariant("eye"),
    variants: getIconVariants("eye"),
  },
  {
    name: "download",
    title: "Download",
    category: "arrows",
    tags: ["import", "export", "save", "download"],
    variant: getDefaultIconVariant("download"),
    variants: getIconVariants("download"),
  },
  {
    name: "upload",
    title: "Upload",
    category: "arrows",
    tags: ["file", "upload"],
    variant: getDefaultIconVariant("upload"),
    variants: getIconVariants("upload"),
  },
  {
    name: "refresh-cw",
    title: "Refresh CW",
    category: "arrows",
    tags: [
      "rotate",
      "reload",
      "rerun",
      "synchronise",
      "synchronize",
      "arrows",
      "circular",
      "cycle",
      "refresh-cw",
    ],
    variant: getDefaultIconVariant("refresh-cw"),
    variants: getIconVariants("refresh-cw"),
  },
  {
    name: "sun",
    title: "Sun",
    category: "accessibility",
    tags: ["brightness", "weather", "light", "summer", "sun"],
    variant: getDefaultIconVariant("sun"),
    variants: getIconVariants("sun"),
  },
  {
    name: "zap",
    title: "Zap",
    category: "connectivity",
    tags: [
      "flash",
      "camera",
      "lightning",
      "electricity",
      "energy",
      "power",
      "quick",
      "zap",
    ],
    variant: getDefaultIconVariant("zap"),
    variants: getIconVariants("zap"),
  },
  {
    name: "play",
    title: "Play",
    category: "arrows",
    tags: ["music", "audio", "video", "start", "run", "play"],
    variant: getDefaultIconVariant("play"),
    variants: getIconVariants("play"),
  },
  {
    name: "shield-alert",
    title: "Shield Alert",
    category: "account",
    tags: [
      "unshielded",
      "cybersecurity",
      "insecure",
      "unsecured",
      "safety",
      "unsafe",
      "protection",
      "unprotected",
      "guardian",
      "unguarded",
      "unarmored",
      "unarmoured",
      "defenseless",
      "defenceless",
      "undefended",
      "defender",
      "blocked",
      "stopped",
      "intercepted",
      "interception",
      "saved",
      "thwarted",
      "threat",
      "prevention",
      "unprevented",
      "antivirus",
      "vigilance",
      "vigilant",
      "detection",
      "detected",
      "scanned",
      "found",
      "exploit",
      "vulnerability",
      "vulnerable",
      "weakness",
      "infection",
      "infected",
      "compromised",
      "data leak",
      "audited",
      "admin",
      "verification",
      "unverified",
      "uncertified",
      "warning",
      "emergency",
      "attention",
      "urgent",
      "alarm",
      "crest",
      "bravery",
      "strength",
      "tough",
      "attacked",
      "damaged",
      "injured",
      "hit",
      "expired",
      "disabled",
      "inactive",
      "error",
      "exclamation mark",
      "!",
      "shield-alert",
    ],
    variant: getDefaultIconVariant("shield-alert"),
    variants: getIconVariants("shield-alert"),
  },
  {
    name: "bot",
    title: "Bot",
    category: "development",
    tags: ["robot", "ai", "chat", "assistant", "bot"],
    variant: getDefaultIconVariant("bot"),
    variants: getIconVariants("bot"),
  },
  {
    name: "folder-open",
    title: "Folder Open",
    category: "files",
    tags: ["directory", "folder-open"],
    variant: getDefaultIconVariant("folder-open"),
    variants: getIconVariants("folder-open"),
  },
  {
    name: "globe",
    title: "Globe",
    category: "navigation",
    tags: ["world", "browser", "language", "translate", "globe"],
    variant: getDefaultIconVariant("globe"),
    variants: getIconVariants("globe"),
  },
  {
    name: "send",
    title: "Send",
    category: "mail",
    tags: [
      "email",
      "message",
      "mail",
      "paper airplane",
      "paper aeroplane",
      "submit",
      "send",
    ],
    variant: getDefaultIconVariant("send"),
    variants: getIconVariants("send"),
  },
  {
    name: "volume-x",
    title: "Volume X",
    category: "connectivity",
    tags: ["music", "sound", "mute", "speaker", "volume-x"],
    variant: getDefaultIconVariant("volume-x"),
    variants: getIconVariants("volume-x"),
  },
  {
    name: "calendar-days",
    title: "Calendar Days",
    category: "time",
    tags: ["date", "month", "year", "event", "calendar-days"],
    variant: getDefaultIconVariant("calendar-days"),
    variants: getIconVariants("calendar-days"),
  },
  {
    name: "pause",
    title: "Pause",
    category: "multimedia",
    tags: ["music", "stop", "pause"],
    variant: getDefaultIconVariant("pause"),
    variants: getIconVariants("pause"),
  },
  {
    name: "share-2",
    title: "Share 2",
    category: "account",
    tags: ["network", "connections", "share-2"],
    variant: getDefaultIconVariant("share-2"),
    variants: getIconVariants("share-2"),
  },
  {
    name: "badge-check",
    title: "Badge Check",
    category: "social",
    tags: ["verified", "check", "badge-check"],
    variant: getDefaultIconVariant("badge-check"),
    variants: getIconVariants("badge-check"),
  },
  {
    name: "inbox",
    title: "Inbox",
    category: "account",
    tags: ["email", "inbox"],
    variant: getDefaultIconVariant("inbox"),
    variants: getIconVariants("inbox"),
  },
  {
    name: "file",
    title: "File",
    category: "files",
    tags: ["document", "file"],
    variant: getDefaultIconVariant("file"),
    variants: getIconVariants("file"),
  },
  {
    name: "credit-card",
    title: "Credit Card",
    category: "account",
    tags: ["bank", "purchase", "payment", "cc", "credit-card"],
    variant: getDefaultIconVariant("credit-card"),
    variants: getIconVariants("credit-card"),
  },
  {
    name: "external-link",
    title: "External Link",
    category: "arrows",
    tags: ["outbound", "open", "share", "external-link"],
    variant: getDefaultIconVariant("external-link"),
    variants: getIconVariants("external-link"),
  },
  {
    name: "ellipsis",
    title: "Ellipsis",
    category: "layout",
    tags: [
      "et cetera",
      "etc",
      "loader",
      "loading",
      "progress",
      "pending",
      "throbber",
      "menu",
      "options",
      "operator",
      "code",
      "coding",
      "spread",
      "rest",
      "more",
      "further",
      "extra",
      "overflow",
      "dots",
      "…",
      "...",
      "ellipsis",
    ],
    variant: getDefaultIconVariant("ellipsis"),
    variants: getIconVariants("ellipsis"),
  },
  {
    name: "grip-vertical",
    title: "Grip Vertical",
    category: "layout",
    tags: ["grab", "dots", "handle", "move", "drag", "grip-vertical"],
    variant: getDefaultIconVariant("grip-vertical"),
    variants: getIconVariants("grip-vertical"),
  },
  {
    name: "paperclip",
    title: "Paperclip",
    category: "text",
    tags: ["attachment", "file", "paperclip"],
    variant: getDefaultIconVariant("paperclip"),
    variants: getIconVariants("paperclip"),
  },
  {
    name: "log-out",
    title: "Log Out",
    category: "arrows",
    tags: ["sign out", "arrow", "exit", "auth", "log-out"],
    variant: getDefaultIconVariant("log-out"),
    variants: getIconVariants("log-out"),
  },
  {
    name: "message-square",
    title: "Message Square",
    category: "social",
    tags: [
      "comment",
      "chat",
      "conversation",
      "dialog",
      "feedback",
      "speech bubble",
      "message-square",
    ],
    variant: getDefaultIconVariant("message-square"),
    variants: getIconVariants("message-square"),
  },
  {
    name: "palette",
    title: "Palette",
    category: "text",
    tags: [
      "colors",
      "colours",
      "theme",
      "scheme",
      "paint",
      "watercolor",
      "watercolour",
      "artist",
      "palette",
    ],
    variant: getDefaultIconVariant("palette"),
    variants: getIconVariants("palette"),
  },
  {
    name: "repeat-2",
    title: "Repeat 2",
    category: "arrows",
    tags: [
      "arrows",
      "retweet",
      "repost",
      "share",
      "repeat",
      "loop",
      "repeat-2",
    ],
    variant: getDefaultIconVariant("repeat-2"),
    variants: getIconVariants("repeat-2"),
  },
  {
    name: "sparkles",
    title: "Sparkles",
    category: "cursors",
    tags: ["stars", "effect", "filter", "night", "magic", "sparkles"],
    variant: getDefaultIconVariant("sparkles"),
    variants: getIconVariants("sparkles"),
  },
  {
    name: "zoom-in",
    title: "Zoom In",
    category: "accessibility",
    tags: ["magnifying glass", "plus", "zoom-in"],
    variant: getDefaultIconVariant("zoom-in"),
    variants: getIconVariants("zoom-in"),
  },
  {
    name: "zoom-out",
    title: "Zoom Out",
    category: "accessibility",
    tags: ["magnifying glass", "plus", "zoom-out"],
    variant: getDefaultIconVariant("zoom-out"),
    variants: getIconVariants("zoom-out"),
  },
  {
    name: "users",
    title: "Users",
    category: "account",
    tags: ["group", "people", "users"],
    variant: getDefaultIconVariant("users"),
    variants: getIconVariants("users"),
  },
  {
    name: "briefcase",
    title: "Briefcase",
    category: "transportation",
    tags: ["work", "bag", "baggage", "folder", "briefcase"],
    variant: getDefaultIconVariant("briefcase"),
    variants: getIconVariants("briefcase"),
  },
  {
    name: "archive",
    title: "Archive",
    category: "files",
    tags: ["index", "backup", "box", "storage", "records", "archive"],
    variant: getDefaultIconVariant("archive"),
    variants: getIconVariants("archive"),
  },
  {
    name: "book-open",
    title: "Book Open",
    category: "text",
    tags: [
      "reading",
      "pages",
      "booklet",
      "magazine",
      "leaflet",
      "pamphlet",
      "library",
      "writing",
      "written",
      "writer",
      "author",
      "story",
      "script",
      "screenplay",
      "fiction",
      "novel",
      "information",
      "knowledge",
      "education",
      "high school",
      "university",
      "college",
      "academy",
      "student",
      "study",
      "learning",
      "homework",
      "research",
      "documentation",
      "revealed",
      "blank",
      "plain",
      "book-open",
    ],
    variant: getDefaultIconVariant("book-open"),
    variants: getIconVariants("book-open"),
  },
  {
    name: "cloud",
    title: "Cloud",
    category: "weather",
    tags: ["weather", "cloud"],
    variant: getDefaultIconVariant("cloud"),
    variants: getIconVariants("cloud"),
  },
  {
    name: "compass",
    title: "Compass",
    category: "navigation",
    tags: ["direction", "north", "east", "south", "west", "browser", "compass"],
    variant: getDefaultIconVariant("compass"),
    variants: getIconVariants("compass"),
  },
  {
    name: "dollar-sign",
    title: "Dollar Sign",
    category: "finance",
    tags: ["currency", "money", "payment", "dollar-sign"],
    variant: getDefaultIconVariant("dollar-sign"),
    variants: getIconVariants("dollar-sign"),
  },
  {
    name: "flag",
    title: "Flag",
    category: "account",
    tags: [
      "report",
      "marker",
      "notification",
      "warning",
      "milestone",
      "goal",
      "notice",
      "signal",
      "attention",
      "banner",
      "flag",
    ],
    variant: getDefaultIconVariant("flag"),
    variants: getIconVariants("flag"),
  },
  {
    name: "key-round",
    title: "Key Round",
    category: "security",
    tags: [
      "password",
      "login",
      "authentication",
      "secure",
      "unlock",
      "key-round",
    ],
    variant: getDefaultIconVariant("key-round"),
    variants: getIconVariants("key-round"),
  },
  {
    name: "layers",
    title: "Layers",
    category: "design",
    tags: [
      "stack",
      "pile",
      "pages",
      "sheets",
      "paperwork",
      "copies",
      "copy",
      "layers",
    ],
    variant: getDefaultIconVariant("layers"),
    variants: getIconVariants("layers"),
  },
  {
    name: "life-buoy",
    title: "Life Buoy",
    category: "accessibility",
    tags: [
      "preserver",
      "life belt",
      "lifesaver",
      "help",
      "rescue",
      "ship",
      "ring",
      "raft",
      "inflatable",
      "wheel",
      "donut",
      "life-buoy",
    ],
    variant: getDefaultIconVariant("life-buoy"),
    variants: getIconVariants("life-buoy"),
  },
  {
    name: "link",
    title: "Link",
    category: "text",
    tags: ["chain", "url", "link"],
    variant: getDefaultIconVariant("link"),
    variants: getIconVariants("link"),
  },
  {
    name: "monitor",
    title: "Monitor",
    category: "connectivity",
    tags: [
      "tv",
      "computer",
      "desktop",
      "screen",
      "display",
      "external display",
      "screen sharing",
      "virtual machine",
      "vm",
      "monitor",
    ],
    variant: getDefaultIconVariant("monitor"),
    variants: getIconVariants("monitor"),
  },
  {
    name: "panel-left",
    title: "Panel Left",
    category: "layout",
    tags: ["primary", "drawer", "panel-left"],
    variant: getDefaultIconVariant("panel-left"),
    variants: getIconVariants("panel-left"),
  },
  {
    name: "pencil",
    title: "Pencil",
    category: "design",
    tags: [
      "rubber",
      "edit",
      "create",
      "draw",
      "sketch",
      "draft",
      "writer",
      "writing",
      "stationery",
      "artist",
      "pencil",
    ],
    variant: getDefaultIconVariant("pencil"),
    variants: getIconVariants("pencil"),
  },
  {
    name: "printer",
    title: "Printer",
    category: "devices",
    tags: ["fax", "office", "device", "printer"],
    variant: getDefaultIconVariant("printer"),
    variants: getIconVariants("printer"),
  },
  {
    name: "qr-code",
    title: "QR Code",
    category: "development",
    tags: [
      "barcode",
      "scan",
      "link",
      "url",
      "information",
      "digital",
      "qr-code",
    ],
    variant: getDefaultIconVariant("qr-code"),
    variants: getIconVariants("qr-code"),
  },
  {
    name: "cloud-upload",
    title: "Cloud Upload",
    category: "arrows",
    tags: ["file", "cloud-upload"],
    variant: getDefaultIconVariant("cloud-upload"),
    variants: getIconVariants("cloud-upload"),
  },
  {
    name: "circle-question-mark",
    title: "Circle Question Mark",
    category: "accessibility",
    tags: ["question mark", "circle-question-mark"],
    variant: getDefaultIconVariant("circle-question-mark"),
    variants: getIconVariants("circle-question-mark"),
  },
  {
    name: "layout-dashboard",
    title: "Layout Dashboard",
    category: "design",
    tags: ["masonry", "brick", "layout-dashboard"],
    variant: getDefaultIconVariant("layout-dashboard"),
    variants: getIconVariants("layout-dashboard"),
  },
  {
    name: "menu",
    title: "Menu",
    category: "layout",
    tags: ["bars", "navigation", "hamburger", "options", "menu"],
    variant: getDefaultIconVariant("menu"),
    variants: getIconVariants("menu"),
  },
  {
    name: "chart-no-axes-column",
    title: "Chart No Axes Column",
    category: "charts",
    tags: [
      "statistics",
      "analytics",
      "diagram",
      "graph",
      "chart-no-axes-column",
    ],
    variant: getDefaultIconVariant("chart-no-axes-column"),
    variants: getIconVariants("chart-no-axes-column"),
  },
  {
    name: "clipboard-list",
    title: "Clipboard List",
    category: "text",
    tags: ["copy", "paste", "tasks", "clipboard-list"],
    variant: getDefaultIconVariant("clipboard-list"),
    variants: getIconVariants("clipboard-list"),
  },
  {
    name: "activity",
    title: "Activity",
    category: "medical",
    tags: [
      "pulse",
      "action",
      "motion",
      "movement",
      "exercise",
      "fitness",
      "healthcare",
      "heart rate monitor",
      "vital signs",
      "vitals",
      "emergency room",
      "er",
      "intensive care",
      "hospital",
      "defibrillator",
      "earthquake",
      "seismic",
      "magnitude",
      "richter scale",
      "aftershock",
      "tremor",
      "shockwave",
      "audio",
      "waveform",
      "synthesizer",
      "synthesiser",
      "music",
      "activity",
    ],
    variant: getDefaultIconVariant("activity"),
    variants: getIconVariants("activity"),
  },
  {
    name: "user-plus",
    title: "User Plus",
    category: "account",
    tags: ["new", "add", "create", "follow", "subscribe", "user-plus"],
    variant: getDefaultIconVariant("user-plus"),
    variants: getIconVariants("user-plus"),
  },
  {
    name: "package",
    title: "Package",
    category: "files",
    tags: [
      "box",
      "container",
      "storage",
      "sealed",
      "delivery",
      "undelivered",
      "unopened",
      "packed",
      "archive",
      "zip",
      "module",
      "package",
    ],
    variant: getDefaultIconVariant("package"),
    variants: getIconVariants("package"),
  },
  {
    name: "circle-x",
    title: "Circle X",
    category: "math",
    tags: [
      "cancel",
      "close",
      "delete",
      "remove",
      "times",
      "clear",
      "error",
      "incorrect",
      "wrong",
      "mistake",
      "failure",
      "linter",
      "multiply",
      "multiplication",
      "circle-x",
    ],
    variant: getDefaultIconVariant("circle-x"),
    variants: getIconVariants("circle-x"),
  },
  {
    name: "building-2",
    title: "Building 2",
    category: "account",
    tags: [
      "business",
      "company",
      "enterprise",
      "skyscraper",
      "organisation",
      "organization",
      "city",
      "building-complex",
      "building-2",
    ],
    variant: getDefaultIconVariant("building-2"),
    variants: getIconVariants("building-2"),
  },
  {
    name: "history",
    title: "History",
    category: "arrows",
    tags: [
      "history",
      "time",
      "redo",
      "undo",
      "rewind",
      "timeline",
      "version",
      "time machine",
      "backup",
      "ccw",
      "rotate-ccw-clock",
    ],
    variant: getDefaultIconVariant("history"),
    variants: getIconVariants("history"),
  },
  {
    name: "panel-left-open",
    title: "Panel Left Open",
    category: "layout",
    tags: [
      "primary",
      "drawer",
      "show",
      "reveal",
      "chevron",
      "right",
      ">",
      "panel-left-open",
    ],
    variant: getDefaultIconVariant("panel-left-open"),
    variants: getIconVariants("panel-left-open"),
  },
  {
    name: "panel-left-close",
    title: "Panel Left Close",
    category: "layout",
    tags: ["primary", "drawer", "hide", "chevron", "<", "panel-left-close"],
    variant: getDefaultIconVariant("panel-left-close"),
    variants: getIconVariants("panel-left-close"),
  },
  {
    name: "panel-right-open",
    title: "Panel Right Open",
    category: "layout",
    tags: [
      "sidebar",
      "secondary",
      "drawer",
      "show",
      "reveal",
      "chevron",
      "left",
      "<",
      "panel-right-open",
    ],
    variant: getDefaultIconVariant("panel-right-open"),
    variants: getIconVariants("panel-right-open"),
  },
  {
    name: "panel-right-close",
    title: "Panel Right Close",
    category: "layout",
    tags: [
      "sidebar",
      "secondary",
      "drawer",
      "hide",
      "chevron",
      ">",
      "panel-right-close",
    ],
    variant: getDefaultIconVariant("panel-right-close"),
    variants: getIconVariants("panel-right-close"),
  },
  {
    name: "ellipsis-vertical",
    title: "Ellipsis Vertical",
    category: "layout",
    tags: [
      "menu",
      "options",
      "spread",
      "more",
      "further",
      "extra",
      "overflow",
      "dots",
      "…",
      "...",
      "ellipsis-vertical",
    ],
    variant: getDefaultIconVariant("ellipsis-vertical"),
    variants: getIconVariants("ellipsis-vertical"),
  },
  {
    name: "command",
    title: "Command",
    category: "development",
    tags: ["keyboard", "key", "mac", "cmd", "button", "command"],
    variant: getDefaultIconVariant("command"),
    variants: getIconVariants("command"),
  },
  {
    name: "database",
    title: "Database",
    category: "devices",
    tags: [
      "storage",
      "memory",
      "container",
      "tin",
      "pot",
      "bytes",
      "servers",
      "database",
    ],
    variant: getDefaultIconVariant("database"),
    variants: getIconVariants("database"),
  },
  {
    name: "target",
    title: "Target",
    category: "gaming",
    tags: [
      "logo",
      "bullseye",
      "deadline",
      "projects",
      "overview",
      "work",
      "productivity",
      "target",
    ],
    variant: getDefaultIconVariant("target"),
    variants: getIconVariants("target"),
  },
  {
    name: "shield-check",
    title: "Shield Check",
    category: "account",
    tags: [
      "cybersecurity",
      "secured",
      "safety",
      "protection",
      "protected",
      "guardian",
      "guarded",
      "armored",
      "armoured",
      "defense",
      "defence",
      "defended",
      "blocked",
      "threat",
      "prevention",
      "prevented",
      "antivirus",
      "vigilance",
      "vigilant",
      "active",
      "activated",
      "enabled",
      "detection",
      "scanned",
      "found",
      "strength",
      "strong",
      "tough",
      "invincible",
      "invincibility",
      "invulnerable",
      "undamaged",
      "audited",
      "admin",
      "verification",
      "verified",
      "certification",
      "certified",
      "tested",
      "passed",
      "qualified",
      "cleared",
      "cleaned",
      "disinfected",
      "uninfected",
      "task",
      "completed",
      "todo",
      "done",
      "ticked",
      "checked",
      "crest",
      "bravery",
      "shield-check",
    ],
    variant: getDefaultIconVariant("shield-check"),
    variants: getIconVariants("shield-check"),
  },
  {
    name: "server",
    title: "Server",
    category: "development",
    tags: ["cloud", "storage", "server"],
    variant: getDefaultIconVariant("server"),
    variants: getIconVariants("server"),
  },
  {
    name: "wallet-cards",
    title: "Wallet Cards",
    category: "account",
    tags: [
      "wallet",
      "cards",
      "banking",
      "cash",
      "debit",
      "transport",
      "money",
      "finance",
      "pocket",
      "credit",
      "purchase",
      "payment",
      "shopping",
      "retail",
      "consumer",
      "cc",
      "wallet-cards",
    ],
    variant: getDefaultIconVariant("wallet-cards"),
    variants: getIconVariants("wallet-cards"),
  },
  {
    name: "receipt-text",
    title: "Receipt Text",
    category: "finance",
    tags: [
      "bill",
      "voucher",
      "slip",
      "check",
      "counterfoil",
      "details",
      "small print",
      "terms",
      "conditions",
      "contract",
      "receipt-text",
    ],
    variant: getDefaultIconVariant("receipt-text"),
    variants: getIconVariants("receipt-text"),
  },
  {
    name: "shopping-cart",
    title: "Shopping Cart",
    category: "shopping",
    tags: [
      "trolley",
      "cart",
      "basket",
      "e-commerce",
      "store",
      "purchase",
      "products",
      "items",
      "ingredients",
      "shopping-cart",
    ],
    variant: getDefaultIconVariant("shopping-cart"),
    variants: getIconVariants("shopping-cart"),
  },
  {
    name: "shopping-bag",
    title: "Shopping Bag",
    category: "shopping",
    tags: ["ecommerce", "cart", "purchase", "store", "shopping-bag"],
    variant: getDefaultIconVariant("shopping-bag"),
    variants: getIconVariants("shopping-bag"),
  },
  {
    name: "megaphone",
    title: "Megaphone",
    category: "multimedia",
    tags: [
      "advertisement",
      "announcement",
      "attention",
      "alert",
      "loudspeaker",
      "megaphone",
      "notification",
    ],
    variant: getDefaultIconVariant("megaphone"),
    variants: getIconVariants("megaphone"),
  },
  {
    name: "award",
    title: "Award",
    category: "account",
    tags: ["achievement", "badge", "rosette", "prize", "winner", "award"],
    variant: getDefaultIconVariant("award"),
    variants: getIconVariants("award"),
  },
  {
    name: "graduation-cap",
    title: "Graduation Cap",
    category: "buildings",
    tags: [
      "school",
      "university",
      "learn",
      "study",
      "mortarboard",
      "education",
      "ceremony",
      "academic",
      "hat",
      "diploma",
      "bachelor's",
      "master's",
      "doctorate",
      "graduation-cap",
    ],
    variant: getDefaultIconVariant("graduation-cap"),
    variants: getIconVariants("graduation-cap"),
  },
  {
    name: "truck",
    title: "Truck",
    category: "transportation",
    tags: ["delivery", "van", "shipping", "haulage", "lorry", "truck"],
    variant: getDefaultIconVariant("truck"),
    variants: getIconVariants("truck"),
  },
  {
    name: "phone",
    title: "Phone",
    category: "text",
    tags: ["call", "phone"],
    variant: getDefaultIconVariant("phone"),
    variants: getIconVariants("phone"),
  },
  {
    name: "gauge",
    title: "Gauge",
    category: "transportation",
    tags: [
      "dashboard",
      "dial",
      "meter",
      "speed",
      "pressure",
      "measure",
      "level",
      "gauge",
    ],
    variant: getDefaultIconVariant("gauge"),
    variants: getIconVariants("gauge"),
  },
  {
    name: "workflow",
    title: "Workflow",
    category: "development",
    tags: [
      "action",
      "continuous integration",
      "ci",
      "automation",
      "devops",
      "network",
      "node",
      "connection",
      "workflow",
    ],
    variant: getDefaultIconVariant("workflow"),
    variants: getIconVariants("workflow"),
  },
] as const;

export function getIconSvg(
  name: string,
  variant: IconVariant = "duotone",
  size = 24
): string {
  const sourceVariant = variant === "outline" ? "duotone" : variant;
  const entry = Object.entries(svgModules[sourceVariant]).find(([path]) =>
    path.endsWith(`/${name}.svg`)
  );
  if (!entry) {
    throw new Error(`Icon SVG for "${name}" not found in catalog.`);
  }

  let svg = entry[1].trim();

  if (variant === "outline") {
    // Strip the closed tint geometry (<path ... fill-opacity="0.33" ... /> or <rect ... />)
    svg = svg.replace(
      /<(path|rect|circle|polygon)[^>]*fill-opacity=[^>]*\/>\s*/gi,
      ""
    );
  }

  if (size !== 24 && size > 0) {
    svg = svg
      .replace(/width="[0-9]+"/, `width="${size}"`)
      .replace(/height="[0-9]+"/, `height="${size}"`);
  }

  return svg;
}

export const CATEGORY_LABELS: Record<"all" | IconCategory, string> = {
  all: "All",
  accessibility: "Accessibility",
  account: "Account",
  animals: "Animals",
  arrows: "Arrows",
  buildings: "Buildings",
  charts: "Charts",
  communication: "Communication",
  connectivity: "Connectivity",
  cursors: "Cursors",
  design: "Design",
  development: "Development",
  devices: "Devices",
  emoji: "Emoji",
  files: "Files",
  finance: "Finance",
  "food-beverage": "Food Beverage",
  gaming: "Gaming",
  home: "Home",
  layout: "Layout",
  mail: "Mail",
  math: "Math",
  medical: "Medical",
  multimedia: "Multimedia",
  nature: "Nature",
  navigation: "Navigation",
  notifications: "Notifications",
  people: "People",
  photography: "Photography",
  science: "Science",
  seasons: "Seasons",
  security: "Security",
  shapes: "Shapes",
  shopping: "Shopping",
  social: "Social",
  sports: "Sports",
  sustainability: "Sustainability",
  text: "Text",
  time: "Time",
  tools: "Tools",
  transportation: "Transportation",
  travel: "Travel",
  weather: "Weather",
};

export function getCategoryCounts(
  items: readonly IconCatalogItem[] = ICON_CATALOG,
  variant: IconVariantFilter = "all"
): CategoryInfo[] {
  const counts: Partial<Record<IconCategory, number>> = {};
  let total = 0;

  for (const item of items) {
    const itemCount = getIconVariantCount(item, variant);
    counts[item.category] = (counts[item.category] || 0) + itemCount;
    total += itemCount;
  }

  const categoryInfos: CategoryInfo[] = [
    { id: "all", label: CATEGORY_LABELS.all, count: total },
  ];

  for (const category of ICON_CATEGORIES) {
    const count = counts[category] || 0;
    if (count > 0) {
      categoryInfos.push({
        id: category,
        label: CATEGORY_LABELS[category],
        count,
      });
    }
  }

  return categoryInfos;
}

export function getIconCount(
  items: readonly IconCatalogItem[] = ICON_CATALOG,
  variant: IconVariantFilter = "all"
): number {
  return items.reduce(
    (total, item) => total + getIconVariantCount(item, variant),
    0
  );
}
